sudo: false
language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
install:
    - pip install coverage coveralls
script:
    - coverage run --source=eazysvn setup.py test -q
after_success:
    - coveralls
notifications:
    email: false
