language: python
dist: xenial
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - pypy2.7-6.0.0
    - pypy3.5-6.0.0
install:
    - pip install coverage coveralls pytest mock
script:
    - coverage run -m pytest eazysvn.py tests.py
after_success:
    - coveralls
notifications:
    email: false
