sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install:
    - pip install coverage coveralls pytest mock
script:
    - coverage run -m pytest eazysvn.py tests.py
after_success:
    - coveralls
notifications:
    email: false
